### ISSUE TITLE
Still maintain?

### ISSUE THREAD

**Issue by lecorguille** [andrewrothstein/ansible-rstudio-server#2]
Hi,
I have just play with this role. It is really cool and works immediately.

With the ansible-galaxy, there is an issue:
```
Warning message:
R graphics engine version 12 is not supported by this version of RStudio. The Plots tab will be disabled until a newer version of RStudio is installed. 
```

It is fixed with the update you have done on the GitHub repo `rstudio_server_ver : '1.1.447'`
Do you plan to update the galaxy version from the github one ?

Many thanks for this work!

**Comment by FanchTheSystem** [comment]
https://github.com/andrewrothstein/ansible-rstudio-server/pull/3 ;)

**Comment by andrewrothstein** [comment]
barely. I find them useful and hope others do too!
